export enum Province {
    BuenosAires = 'Buenos Aires',
    Catamarca = 'Catamarca',
    Chaco = 'Chaco',
    Chubut = 'Chubut',
    Cordoba = 'Córdoba',
    Corrientes = 'Corrientes',
    EntreRios = 'Entre Ríos',
    Formosa = 'Formosa',
    Jujuy = 'Jujuy',
    LaPampa = 'La Pampa',
    LaRioja = 'La Rioja',
    Mendoza = 'Mendoza',
    Misiones = 'Misiones',
    Neuquen = 'Neuquén',
    RioNegro = 'Río Negro',
    Salta = 'Salta',
    SanJuan = 'San Juan',
    SanLuis = 'San Luis',
    SantaCruz = 'Santa Cruz',
    SantaFe = 'Santa Fe',
    SantiagoDelEstero = 'Santiago del Estero',
    TierraDelFuego = 'Tierra del Fuego',
    Tucuman = 'Tucumán',
    CABA = 'Ciudad Autónoma de Buenos Aires'
}